# Makefile for the multivariate reconciliation paper repository
#
# Common targets:
#   make              Build paper and supplementary PDFs, regenerating needed outputs.
#   make paper        Build multivariate-reconciliation.pdf.
#   make supplement   Build supplementary_material.pdf.
#   make tables       Regenerate all LaTeX table fragments.
#   make figures      Regenerate generated figures.
#   make data         Regenerate cached simulation/application R outputs.
#   make clean        Remove LaTeX auxiliary files.
#   make clean-generated
#                     Remove generated R caches, tables, and figures listed below.

SHELL := /bin/bash

R := Rscript --vanilla
LATEXMK := latexmk
LATEXMKFLAGS := -pdf -interaction=nonstopmode -halt-on-error

.PHONY: all pdf paper supplement data simulation application tables sim-tables app-tables figures sim-figures app-figures pdf-only clean clean-latex clean-generated help

all: pdf

pdf: paper supplement

paper: multivariate-reconciliation.pdf

supplement: supplementary_material.pdf

pdf-only:
	$(LATEXMK) $(LATEXMKFLAGS) multivariate-reconciliation.tex
	$(LATEXMK) $(LATEXMKFLAGS) supplementary_material.tex

# -----------------------------------------------------------------------------
# Files generated by R scripts
# -----------------------------------------------------------------------------

SIM_RDS := \
	Saida/sim_rec1.rds \
	Saida/sim_rec2.rds \
	Saida/sim_rec3.rds \
	Saida/sim_rec4.rds \
	Saida/sim_rec5.rds \
	Saida/sim_rec6.rds \
	Saida/sim_rec7.rds \
	Saida/sim_rec8.rds \
	Saida/sim_rec9.rds

APP_RDS := Saida/app_relrmse.rds
APP_MODEL_RDS := Saida/mod_arima_regiao.rds Saida/mod_var_regiao.rds

SIM_TABLES := \
	Tabelas/Tabs_RMSSE.tex \
	Tabelas/Tabs_sh.tex \
	Tabelas/Tabs_uni.tex \
	Tabelas/Tabs_cov.tex \
	Tabelas/Tabs_sh_mean.tex \
	Tabelas/Tabs_porc_sh.tex \
	Tabelas/Tabs_sh_uni_mean.tex \
	Tabelas/Tabs_porc_sh_uni.tex

APP_TABLES := \
	Tabelas/Tabs_adm_sh.tex \
	Tabelas/Tabs_dem_sh.tex \
	Tabelas/Tabs_var_adm_sh.tex \
	Tabelas/Tabs_var_dem_sh.tex

SIM_FIGS := \
	Imagens/1.pdf \
	Imagens/2.pdf \
	Imagens/3.pdf \
	Imagens/4.pdf \
	Imagens/5.pdf \
	Imagens/6.pdf \
	Imagens/7.pdf \
	Imagens/8.pdf \
	Imagens/9.pdf

APP_FIGS := \
	Imagens/fig_emprego_br.pdf \
	Imagens/fig_emprego_reg.pdf \
	Imagens/fig_emprego_uf.pdf \
	Imagens/mapa_reg.pdf

# Static figures included by the paper are not built here:
#   Imagens/diagrama_mult.pdf, Imagens/Diagrama_sim.pdf, Imagens/validacao.pdf

SIM_SCRIPTS := \
	R/simulation.R \
	R/simulation_setup.R \
	R/simulation_functions.R \
	R/reconcile.R \
	R/helpers.R

APP_SCRIPTS := \
	R/application.R \
	R/application_data.R \
	R/application_S.R \
	R/reconcile.R \
	R/helpers.R

TABLE_SCRIPTS := R/tables.R

# -----------------------------------------------------------------------------
# Directory creation
# -----------------------------------------------------------------------------

Saida Tabelas Imagens:
	mkdir -p $@

# -----------------------------------------------------------------------------
# Cached data/model outputs
# -----------------------------------------------------------------------------

data: simulation application

simulation: $(SIM_RDS)

$(SIM_RDS) &: $(SIM_SCRIPTS) | Saida
	$(R) R/simulation.R

application: $(APP_RDS)

$(APP_RDS): $(APP_SCRIPTS) Dados/Dados_emprego_rgi.csv | Saida
	$(R) R/application.R

# -----------------------------------------------------------------------------
# Tables
# GNU make grouped targets (&:) are used because each script writes several files.
# -----------------------------------------------------------------------------

tables: sim-tables app-tables

sim-tables: $(SIM_TABLES)

$(SIM_TABLES) &: R/simulation_tables.R $(TABLE_SCRIPTS) $(SIM_SCRIPTS) $(SIM_RDS) | Tabelas
	$(R) R/simulation_tables.R

app-tables: $(APP_TABLES)

$(APP_TABLES) &: R/application_tables.R $(TABLE_SCRIPTS) $(APP_SCRIPTS) $(APP_RDS) | Tabelas
	$(R) R/application_tables.R

# -----------------------------------------------------------------------------
# Figures
# GNU make grouped targets (&:) are used because each script writes several files.
# -----------------------------------------------------------------------------

figures: sim-figures app-figures

sim-figures: $(SIM_FIGS)

$(SIM_FIGS) &: R/simulation_figures.R R/simulation_setup.R R/simulation_functions.R R/helpers.R | Imagens
	$(R) R/simulation_figures.R

app-figures: $(APP_FIGS)

$(APP_FIGS) &: R/application_figures.R R/application_data.R Dados/Dados_emprego_rgi.csv | Imagens
	$(R) R/application_figures.R

# -----------------------------------------------------------------------------
# PDFs
# -----------------------------------------------------------------------------

multivariate-reconciliation.pdf: multivariate-reconciliation.tex cas-refs.bib elsarticle.cls elsarticle-harv.bst $(SIM_TABLES) $(APP_TABLES) $(APP_FIGS)
	$(LATEXMK) $(LATEXMKFLAGS) multivariate-reconciliation.tex

supplementary_material.pdf: supplementary_material.tex cas-refs.bib elsarticle.cls elsarticle-harv.bst $(SIM_TABLES) $(APP_TABLES) $(SIM_FIGS)
	$(LATEXMK) $(LATEXMKFLAGS) supplementary_material.tex

# -----------------------------------------------------------------------------
# Cleaning
# -----------------------------------------------------------------------------

clean: clean-latex

clean-latex:
	$(LATEXMK) -c multivariate-reconciliation.tex
	$(LATEXMK) -c supplementary_material.tex

clean-generated:
	rm -f $(SIM_RDS) $(APP_RDS) $(APP_MODEL_RDS)
	rm -f $(SIM_TABLES) $(APP_TABLES)
	rm -f $(SIM_FIGS) $(APP_FIGS)

help:
	@sed -n '1,18p' Makefile
